#pragma once

#include <windows.h>
#include <d3dkmthk.h>
// Minimal NTSTATUS definition if not provided
#ifndef NTSTATUS
typedef LONG NTSTATUS;
#endif

// Function pointer typedefs matching signatures from d3dkmthk.h
using PFN_D3DKMT_OPENADAPTERFROMHDC = NTSTATUS (WINAPI*)(D3DKMT_OPENADAPTERFROMHDC*);
using PFN_D3DKMT_OPENADAPTERFROMDEVICENAME = NTSTATUS (WINAPI*)(D3DKMT_OPENADAPTERFROMDEVICENAME*);
using PFN_D3DKMT_CREATEDEVICE = NTSTATUS (WINAPI*)(D3DKMT_CREATEDEVICE*);
using PFN_D3DKMT_CREATECONTEXT = NTSTATUS (WINAPI*)(D3DKMT_CREATECONTEXT*);
using PFN_D3DKMT_DESTROYDEVICE = NTSTATUS (WINAPI*)(const D3DKMT_DESTROYDEVICE*);
using PFN_D3DKMT_DESTROYCONTEXT = NTSTATUS (WINAPI*)(const D3DKMT_DESTROYCONTEXT*);
using PFN_D3DKMT_PRESENT = NTSTATUS (WINAPI*)(D3DKMT_PRESENT*);

using PFN_D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME = NTSTATUS (WINAPI*)(D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME*);
using PFN_D3DKMT_QUERYADAPTERINFO = NTSTATUS(WINAPI*)(D3DKMT_QUERYADAPTERINFO*);
using PFN_D3DKMT_OPENRESOURCE = NTSTATUS(WINAPI*)(D3DKMT_OPENRESOURCE*);
using PFN_D3DKMT_OPENRESOURCEFROMNTHANDLE = NTSTATUS(WINAPI*)(D3DKMT_OPENRESOURCEFROMNTHANDLE*);
using PFN_D3DKMT_QUERYRESOURCEINFO = NTSTATUS(WINAPI*)(D3DKMT_QUERYRESOURCEINFO*);
using PFN_D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE = NTSTATUS(WINAPI*)(D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE*);
using PFN_D3DKMT_CREATEALLOCATION = NTSTATUS(WINAPI*)(D3DKMT_CREATEALLOCATION*);
using PFN_D3DKMT_DESTROYALLOCATION = NTSTATUS(WINAPI*)(D3DKMT_DESTROYALLOCATION*);
using PFN_D3DKMT_GETDEVICESTATE = NTSTATUS(WINAPI*)(D3DKMT_GETDEVICESTATE*);
using PFN_D3DKMT_SETGAMMARAMP = NTSTATUS(WINAPI*)(D3DKMT_SETGAMMARAMP*);
using PFN_D3DKMT_WAITFORVERTICALBLANKEVENT = NTSTATUS(WINAPI*)(D3DKMT_WAITFORVERTICALBLANKEVENT*);

// Additional KMT interfaces
using PFN_D3DKMT_SUBMITCOMMAND = NTSTATUS (WINAPI*)(D3DKMT_SUBMITCOMMAND*);
using PFN_D3DKMT_CREATEHWQUEUE = NTSTATUS (WINAPI*)(D3DKMT_CREATEHWQUEUE*);
using PFN_D3DKMT_DESTROYHWQUEUE = NTSTATUS (WINAPI*)(D3DKMT_DESTROYHWQUEUE*);
using PFN_D3DKMT_ENUMADAPTERS = NTSTATUS (WINAPI*)(D3DKMT_ENUMADAPTERS*);
using PFN_D3DKMT_LOCK = NTSTATUS (WINAPI*)(D3DKMT_LOCK*);
using PFN_D3DKMT_UNLOCK = NTSTATUS (WINAPI*)(D3DKMT_UNLOCK*);

using PFN_D3DKMT_RENDER = NTSTATUS(WINAPI*)(D3DKMT_RENDER*);
using PFN_D3DKMT_FLIPOVERLAY = NTSTATUS(WINAPI*)(D3DKMT_FLIPOVERLAY*);
using PFN_D3DKMT_CREATEOVERLAY = NTSTATUS(WINAPI*)(D3DKMT_CREATEOVERLAY*);
using PFN_D3DKMT_UPDATEOVERLAY = NTSTATUS(WINAPI*)(D3DKMT_UPDATEOVERLAY*);
using PFN_D3DKMT_SETVIDPNSOURCEOWNER = NTSTATUS(WINAPI*)(D3DKMT_SETVIDPNSOURCEOWNER*);
using PFN_D3DKMT_PRESENT_MULTIPLANE_OVERLAY = NTSTATUS(WINAPI*)(D3DKMT_PRESENT_MULTIPLANE_OVERLAY*);

// Generic pointer type for newer KMT functions where specific structs may be unavailable
using PFN_D3DKMT_GENERIC = NTSTATUS (WINAPI*)(void*);

// Additional PFN typedefs for newer/extended KMT functions
using PFN_D3DKMT_CREATEALLOCATION2 = NTSTATUS (WINAPI*)(D3DKMT_CREATEALLOCATION*);
using PFN_D3DKMT_CONNECTDOORBELL = NTSTATUS (WINAPI*)(D3DKMT_CONNECT_DOORBELL*);
using PFN_D3DKMT_CREATEDOORBELL = NTSTATUS (WINAPI*)(D3DKMT_CREATE_DOORBELL*);
using PFN_D3DKMT_CREATEDCFROMMEMORY = NTSTATUS (WINAPI*)(D3DKMT_CREATEDCFROMMEMORY*);
using PFN_D3DKMT_CREATEHWCONTEXT = NTSTATUS (WINAPI*)(D3DKMT_CREATEHWCONTEXT*);
using PFN_D3DKMT_CREATENATIVEFENCE = NTSTATUS (WINAPI*)(D3DKMT_CREATENATIVEFENCE*);
using PFN_D3DKMT_ENUMADAPTERS2 = NTSTATUS (WINAPI*)(D3DKMT_ENUMADAPTERS2*);
using PFN_D3DKMT_ENUMADAPTERS3 = NTSTATUS (WINAPI*)(D3DKMT_ENUMADAPTERS3*);
using PFN_D3DKMT_ESCAPE = NTSTATUS (WINAPI*)(D3DKMT_ESCAPE*);
using PFN_D3DKMT_GETDISPLAYMODELIST = NTSTATUS (WINAPI*)(D3DKMT_GETDISPLAYMODELIST*);
using PFN_D3DKMT_GETPRESENTHISTORY = NTSTATUS (WINAPI*)(D3DKMT_GETPRESENTHISTORY*);
using PFN_D3DKMT_LOCK2 = NTSTATUS (WINAPI*)(D3DKMT_LOCK2*);
using PFN_D3DKMT_MAPGPUVIRTUALADDRESS = NTSTATUS (WINAPI*)(D3DDDI_MAPGPUVIRTUALADDRESS*);
using PFN_D3DKMT_OFFERALLOCATIONS = NTSTATUS (WINAPI*)(D3DKMT_OFFERALLOCATIONS*);
using PFN_D3DKMT_OPENRESOURCE2 = NTSTATUS (WINAPI*)(D3DKMT_OPENRESOURCE*);
using PFN_D3DKMT_PRESENTMULTIPLANEOVERLAY2 = NTSTATUS (WINAPI*)(D3DKMT_PRESENT_MULTIPLANE_OVERLAY2*);
using PFN_D3DKMT_PRESENTMULTIPLANEOVERLAY3 = NTSTATUS (WINAPI*)(D3DKMT_PRESENT_MULTIPLANE_OVERLAY3*);
using PFN_D3DKMT_PRESENT_REDIRECTED = NTSTATUS (WINAPI*)(D3DKMT_PRESENT_REDIRECTED*);
using PFN_D3DKMT_SETDISPLAYMODE = NTSTATUS (WINAPI*)(D3DKMT_SETDISPLAYMODE*);
using PFN_D3DKMT_SUBMITCOMMANDTOHWQUEUE = NTSTATUS (WINAPI*)(D3DKMT_SUBMITCOMMANDTOHWQUEUE*);
using PFN_D3DKMT_SUBMITPRESENTBLTTOHWQUEUE = NTSTATUS (WINAPI*)(D3DKMT_SUBMITPRESENTBLTTOHWQUEUE*);
using PFN_D3DKMT_SUBMITPRESENTTOHWQUEUE = NTSTATUS (WINAPI*)(D3DKMT_SUBMITPRESENTTOHWQUEUE*);

// Note: these typedefs rely on structs defined in d3dkmthk.h being available.

class KMTInterceptor {
public:
    static bool Initialize();
    static void Shutdown();

private:
    static void InstallHooks();
    static void RemoveHooks();

    // 钩子函数
    static NTSTATUS WINAPI Hooked_D3DKMTOpenAdapterFromHdc(D3DKMT_OPENADAPTERFROMHDC* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTOpenAdapterFromDeviceName(D3DKMT_OPENADAPTERFROMDEVICENAME* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateDevice(D3DKMT_CREATEDEVICE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateContext(D3DKMT_CREATECONTEXT* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTDestroyDevice(const D3DKMT_DESTROYDEVICE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTDestroyContext(const D3DKMT_DESTROYCONTEXT* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTPresent(D3DKMT_PRESENT* pData);

    static NTSTATUS WINAPI Hooked_D3DKMTOpenAdapterFromGdiDisplayName(D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTQueryAdapterInfo(const D3DKMT_QUERYADAPTERINFO* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTOpenResource(D3DKMT_OPENRESOURCE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTOpenResourceFromNtHandle(D3DKMT_OPENRESOURCEFROMNTHANDLE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTQueryResourceInfo(D3DKMT_QUERYRESOURCEINFO* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTQueryResourceInfoFromNtHandle(D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateAllocation(D3DKMT_CREATEALLOCATION* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTDestroyAllocation(const D3DKMT_DESTROYALLOCATION* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTGetDeviceState(D3DKMT_GETDEVICESTATE* pData);

    // Additional hooks
    static NTSTATUS WINAPI Hooked_D3DKMTSetGammaRamp(const D3DKMT_SETGAMMARAMP* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTWaitForVerticalBlankEvent(const D3DKMT_WAITFORVERTICALBLANKEVENT* pData);

    // New hooks for core KMT interfaces
    static NTSTATUS WINAPI Hooked_D3DKMTSubmitCommand(D3DKMT_SUBMITCOMMAND* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateHwQueue(D3DKMT_CREATEHWQUEUE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTDestroyHwQueue(D3DKMT_DESTROYHWQUEUE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTEnumAdapters(D3DKMT_ENUMADAPTERS* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTLock(D3DKMT_LOCK* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTUnlock(D3DKMT_UNLOCK* pData);

    // New hook for Render
    static NTSTATUS WINAPI Hooked_D3DKMTRender(D3DKMT_RENDER* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTFlipOverlay(D3DKMT_FLIPOVERLAY* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateOverlay(D3DKMT_CREATEOVERLAY* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTUpdateOverlay(D3DKMT_UPDATEOVERLAY* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTSetVidPnSourceOwner(D3DKMT_SETVIDPNSOURCEOWNER* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTPresentMultiPlaneOverlay(D3DKMT_PRESENT_MULTIPLANE_OVERLAY* pData);

    // Additional newer hooks requested by user (use concrete typed signatures)
    static NTSTATUS WINAPI Hooked_D3DKMTCreateAllocation2(D3DKMT_CREATEALLOCATION* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTConnectDoorbell(D3DKMT_CONNECT_DOORBELL* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateDoorbell(D3DKMT_CREATE_DOORBELL* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateDCFromMemory(D3DKMT_CREATEDCFROMMEMORY* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateHwContext(D3DKMT_CREATEHWCONTEXT* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTCreateNativeFence(D3DKMT_CREATENATIVEFENCE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTEnumAdapters2(D3DKMT_ENUMADAPTERS2* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTEnumAdapters3(D3DKMT_ENUMADAPTERS3* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTEscape(D3DKMT_ESCAPE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTGetDisplayModeList(D3DKMT_GETDISPLAYMODELIST* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTGetPresentHistory(D3DKMT_GETPRESENTHISTORY* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTLock2(D3DKMT_LOCK2* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTMapGpuVirtualAddress(D3DDDI_MAPGPUVIRTUALADDRESS* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTOfferAllocations(D3DKMT_OFFERALLOCATIONS* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTOpenResource2(D3DKMT_OPENRESOURCE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTPresentMultiPlaneOverlay2(D3DKMT_PRESENT_MULTIPLANE_OVERLAY2* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTPresentMultiPlaneOverlay3(D3DKMT_PRESENT_MULTIPLANE_OVERLAY3* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTPresentRedirected(D3DKMT_PRESENT_REDIRECTED* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTSetDisplayMode(D3DKMT_SETDISPLAYMODE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTSubmitCommandToHwQueue(D3DKMT_SUBMITCOMMANDTOHWQUEUE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTSubmitPresentBltToHwQueue(D3DKMT_SUBMITPRESENTBLTTOHWQUEUE* pData);
    static NTSTATUS WINAPI Hooked_D3DKMTSubmitPresentToHwQueue(D3DKMT_SUBMITPRESENTTOHWQUEUE* pData);

    static HMODULE s_hGdi32;
    // 原始函数指针
    static PFN_D3DKMT_OPENADAPTERFROMHDC s_OriginalOpenAdapterFromHdc;
    static PFN_D3DKMT_OPENADAPTERFROMDEVICENAME s_OriginalOpenAdapterFromDeviceName;
    static PFN_D3DKMT_CREATEDEVICE s_OriginalCreateDevice;
    static PFN_D3DKMT_CREATECONTEXT s_OriginalCreateContext;
    static PFN_D3DKMT_DESTROYDEVICE s_OriginalDestroyDevice;
    static PFN_D3DKMT_DESTROYCONTEXT s_OriginalDestroyContext;
    static PFN_D3DKMT_PRESENT s_OriginalPresent;

    static PFN_D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME s_OriginalOpenAdapterFromGdiDisplayName;
    static PFN_D3DKMT_QUERYADAPTERINFO s_OriginalQueryAdapterInfo;
    static PFN_D3DKMT_OPENRESOURCE s_OriginalOpenResource;
    static PFN_D3DKMT_OPENRESOURCEFROMNTHANDLE s_OriginalOpenResourceFromNtHandle;
    static PFN_D3DKMT_QUERYRESOURCEINFO s_OriginalQueryResourceInfo;
    static PFN_D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE s_OriginalQueryResourceInfoFromNtHandle;
    static PFN_D3DKMT_CREATEALLOCATION s_OriginalCreateAllocation;
    static PFN_D3DKMT_DESTROYALLOCATION s_OriginalDestroyAllocation;
    static PFN_D3DKMT_GETDEVICESTATE s_OriginalGetDeviceState;
    static PFN_D3DKMT_SETGAMMARAMP s_OriginalSetGammaRamp;
    static PFN_D3DKMT_WAITFORVERTICALBLANKEVENT s_OriginalWaitForVerticalBlankEvent;

    // Original pointers for new interfaces
    static PFN_D3DKMT_SUBMITCOMMAND s_OriginalSubmitCommand;
    static PFN_D3DKMT_CREATEHWQUEUE s_OriginalCreateHwQueue;
    static PFN_D3DKMT_DESTROYHWQUEUE s_OriginalDestroyHwQueue;
    static PFN_D3DKMT_ENUMADAPTERS s_OriginalEnumAdapters;
    static PFN_D3DKMT_LOCK s_OriginalLock;
    static PFN_D3DKMT_UNLOCK s_OriginalUnlock;

    // Original pointer for render
    static PFN_D3DKMT_RENDER s_OriginalRender;
    static PFN_D3DKMT_FLIPOVERLAY s_OriginalFlipOverlay;
    static PFN_D3DKMT_CREATEOVERLAY s_OriginalCreateOverlay;
    static PFN_D3DKMT_UPDATEOVERLAY s_OriginalUpdateOverlay;
    static PFN_D3DKMT_SETVIDPNSOURCEOWNER s_OriginalSetVidPnSourceOwner;
    static PFN_D3DKMT_PRESENT_MULTIPLANE_OVERLAY s_OriginalPresentMultiPlaneOverlay;

    // Generic originals for newer functions
    static PFN_D3DKMT_CREATEALLOCATION2 s_OriginalCreateAllocation2;
    static PFN_D3DKMT_CONNECTDOORBELL s_OriginalConnectDoorbell;
    static PFN_D3DKMT_CREATEDOORBELL s_OriginalCreateDoorbell;
    static PFN_D3DKMT_CREATEDCFROMMEMORY s_OriginalCreateDCFromMemory;
    static PFN_D3DKMT_CREATEHWCONTEXT s_OriginalCreateHwContext;
    static PFN_D3DKMT_CREATENATIVEFENCE s_OriginalCreateNativeFence;
    static PFN_D3DKMT_ENUMADAPTERS2 s_OriginalEnumAdapters2;
    static PFN_D3DKMT_ENUMADAPTERS3 s_OriginalEnumAdapters3;
    static PFN_D3DKMT_ESCAPE s_OriginalEscape;
    static PFN_D3DKMT_GETDISPLAYMODELIST s_OriginalGetDisplayModeList;
    static PFN_D3DKMT_GETPRESENTHISTORY s_OriginalGetPresentHistory;
    static PFN_D3DKMT_LOCK2 s_OriginalLock2;
    static PFN_D3DKMT_MAPGPUVIRTUALADDRESS s_OriginalMapGpuVirtualAddress;
    static PFN_D3DKMT_OFFERALLOCATIONS s_OriginalOfferAllocations;
    static PFN_D3DKMT_OPENRESOURCE2 s_OriginalOpenResource2;
    static PFN_D3DKMT_PRESENTMULTIPLANEOVERLAY2 s_OriginalPresentMultiPlaneOverlay2;
    static PFN_D3DKMT_PRESENTMULTIPLANEOVERLAY3 s_OriginalPresentMultiPlaneOverlay3;
    static PFN_D3DKMT_PRESENT_REDIRECTED s_OriginalPresentRedirected; // if not defined, this will be a custom typedef in cpp
    static PFN_D3DKMT_SETDISPLAYMODE s_OriginalSetDisplayMode;
    static PFN_D3DKMT_SUBMITCOMMANDTOHWQUEUE s_OriginalSubmitCommandToHwQueue;
    static PFN_D3DKMT_SUBMITPRESENTBLTTOHWQUEUE s_OriginalSubmitPresentBltToHwQueue;
    static PFN_D3DKMT_SUBMITPRESENTTOHWQUEUE s_OriginalSubmitPresentToHwQueue;
};
